#
# RNA-seq config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content

custom_data:
    my_stats:
        file_format: 'csv'
        section_name: 'General Metrics'
        description: ' of sequenced data'
        plot_type: 'table'
        pconfig:
            namespace: 'stats'
            id: 'stats'
            title: 'General Statistics'
            save_file: true
            col1_header: 'Sample ID'
        headers:
            Sample_name:
              title: 'Sample Name'
              scale: false
              format: '{:.0f}'
              placement: 2000
            Number_of_reads:
              title: 'Total Reads'
              scale: 'YlGnBu'
              format: '{:,.0f}'
              placement: 4000
            Number_of_rRNA:
              title: 'rRNA'
              scale: 'RdYlGn-rev'
              format: '{:,.0f}'
              hidden: true
              placement: 5000
            Percent_of_rRNA:
              title: 'rRNA (%)'
              min: 0
              max: 100
              scale: 'RdYlGn-rev'
              suffix: '%'
              format: '{:,.1f}'
              placement: 6000
            Strandness:
              scale: false
              placement: 3000
            Number_of_aligned_reads:
              title: 'Aligned Reads'
              scale: 'RdYlGn'
              format: '{:,0f}'
              hidden: true
              placement: 7000
            Percent_of_aligned_reads:
              title: 'Aligned Reads (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              suffix: '%'
              format: '{:,.1f}'
              placement: 8000
            Number_of_uniquely_aligned_reads:
              title: 'Unique Reads'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 9000
            Percent_uniquely_aligned_reads:
              title: 'Unique Reads (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              suffix: '%'
              format: '{:,.1f}'
              placement: 10000
            Number_of_multiple_aligned_reads:
              title: 'Multiple Reads'
              scale: 'RdYlGn-rev'
              format: '{:,0f}'
              hidden: true
              placement: 11000
            Percent_multiple_aligned:
              title: 'Multiple Reads (%)'
              min: 0
              max: 100
              scale: 'RdYlGn-rev'
              suffix: '%'
              format: '{:,.1f}'
              placement: 12000
            Number_of_duplicates:
              title: 'Duplicates'
              scale: 'RdYlGn-rev'
              format: '{:,0f}'
              hidden: true
              placement: 13000
            Percent_duplicates:
              title: 'Duplicates (%)'
              min: 0
              max: 100
              scale: 'RdYlGn-rev'
              suffix: '%'
              format: '{:,.1f}'
              placement: 14000

    gene_type:
       file_format: 'csv'
       section_name: 'Expressed Genes'
       description: 'with a TPM value > 1 are considered. The number of expressed genes per sample was splitted into the 5 most abundant classes following the known gene annotations.'
       plot_type: 'bargraph'
       pconfig:
            namespace: 'genetype'
            id: 'genetype'
            title: 'Expressed Genes'
            ylab: 'Number of expressed genes (TPM>1)'
            scale: 'Pastel1'

    gene_saturation:
       file_format: 'tsv'
       section_name: 'Gene-based saturation'
       description: 'plot showing the number of detected genes for a given set of subsampling values.'
       plot_type: 'linegraph'
       pconfig:
            namespace: 'gene saturation'
            id: 'genesaturation'
            title: 'Gene-based Saturation'
            ylab: 'Number of detected genes'
            xlab: 'Number of reads (M)'

sp:
   my_stats:
      fn: '*.stats'
   gene_type:
      fn: '*genetype.txt'
   gene_saturation:
      fn: '*gcurve.txt'


table_cond_formatting_rules:
    Percent_of_rRNA:
        pass:
            - lt: 10
        warn:
            - gt: 10
        fail:
            - gt: 20
    Percent_of_aligned_reads:
        pass:
            - gt: 80
        warn:
            - lt: 80
        fail:
            - lt: 50
    Percent_duplicates:
        pass:
            - lt: 35
        warn:
            - gt: 35
        fail:
            - gt: 50


################################
## Clean sample names

extra_fn_clean_exts:
    - 'gcurve.txt'

###############################
## Modules 

##module_order:
##  - fastqc
##  - cutadapt
##  - snpeff

module_order:
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      path_filters:
        - "*_R1_fastqc.zip"
        - "*_R2_fastqc.zip"
  - cutadapt
  - fastqc:
      name: "FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "This section of the report shows FastQC results after adapter trimming."
      target: ""
      path_filters:
        - "*_R1_trimmed_fastqc.zip"
        - "*_R2_trimmed_fastqc.zip"
  - snpeff

#############################
## Display

report_section_order:
  stats:
    order: 1
  gene_saturation:
    order: -400
  gene_type:
    order: -500
  DupRadar:
    order: -600 
  sample-pca:
    order: -800
  sample-correlation:
    order: -900
  software_versions:
    order: -1000
  summary:
    order: -1100

table_columns_visible:
    FastQC:
        percent_duplicates: False

preseq:
   notrim: true

plots_force_interactive: True
